ProjectMK/Attendance/urls.py
from django.urls import path
from . import views

app_name="Attendance"

urlpatterns=[
    path("",views.index,name="index")
]

ProjectMK/ProjectMK/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/',include("hello.urls")),
    path('newyear/',include("newyear.urls")),
    path('mytasks/',include("mytasks.urls"))
]

ProjectMK/hello/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path("",views.index,name="index"),
    path("<str:name>", views.greet,name="greet")
]

ProjectMK/mytasks/urls.py
from django.urls import path
from . import views

app_name="mytasks"

urlpatterns=[
    path("",views.index,name="index"),
    path("add",views.add,name="add")
]

ProjectMK/newyear/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path("",views.index,name="index")
]

ProjectMK/tasks/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path("",views.index,name="index")
]

ProjectMK/Attendance/models.py
from django.db import models

# Create your models here.

ProjectMK/Attendance/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"Attendance/index.html")

ProjectMK/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"hello/index.html")
def greet(request,name):
    return render(request,"hello/greet.html",{
        "name":name.capitalize()
    })

ProjectMK/mytasks/views.py
from enum import auto
from logging import PlaceHolder
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

class NewTaskForm(forms.Form):
    task=forms.CharField(label="New Task")
    priority=forms.IntegerField(label="Priority",min_value=1,max_value=5)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"]=[]
    return render(request,"mytasks/index.html",{
        "tasks":request.session["tasks"]
    })

def add(request):
    if request.method=="POST":
        form=NewTaskForm(request.POST)
        if form.is_valid():
            task=form.cleaned_data["task"]
            request.session["tasks"]+=[task]
            return HttpResponseRedirect(reverse("mytasks:index"))
        else:
            return render(request,"mytasks/add.html",{
                "form":form
            })
    return render(request,"mytasks/add.html",{
        "form":NewTaskForm()
        })

ProjectMK/newyear/views.py
import datetime

from django.shortcuts import render

# Create your views here.
def index(request):
    now=datetime.datetime.now()
    return render(request,"newyear/index.html",{
        "newyear":now.day==1 and now.month==1
    })

ProjectMK/tasks/views.py
from django.shortcuts import render

tasks=["foo","bar","baz"]

# Create your views here.
def index(request):
    return render(request,"tasks/index.html",{
        "tasks":tasks
    })

ProjectMK/Attendance/templates/Attendance/index.html
{%  extends "Attendance/layout.html" %}
{% block body %}

<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-lg-7 text-center text-lg-start">
        <h1 class="display-4 fw-bold lh-1 mb-3">Attendance portal for Allahabad University student</h1>
        <p class="col-lg-10 fs-4">Since there is no website to check attendance in so called 'oxford university of east' , so I tried creating one</p>
      </div>
      <div class="col-md-10 mx-auto col-lg-5">
        <form class="p-4 p-md-5 border rounded-3 bg-light">
          <div class="form-floating mb-3">
            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email address</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
          </div>
          <div class="checkbox mb-3">
            <label>
              <input type="checkbox" value="remember-me"> Remember me
            </label>
          </div>
          <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
          <hr class="my-4">
          <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

ProjectMK/Attendance/templates/Attendance/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Attendance</title>
        <meta charset="utf-8">
        <meta name="viewport" content="device-width,initial-scale=1"
        <!-- CSS only -->
        <link href="{% static 'Attendance/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <div class="b-example-divider"></div>

  <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'Attendance:index' %}" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">About</a></li>
      </ul>

      <div class="col-md-3 text-end">
        <button type="button" class="btn btn-outline-primary me-2">Login</button>
        <button type="button" class="btn btn-primary">Register</button>
      </div>
    </header>
  </div>
        {% block body %}
        {% endblock %}
    </body>
</html>

ProjectMK/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>
    </head>
    <body>
        <h1>Hello, {{name}}!</h1>
    </body>
</html>

ProjectMK/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>
    </head>
    <body>
        <h1>Hello world</h1>
    </body>
</html>

ProjectMK/mytasks/templates/mytasks/add.html
{% extends "mytasks/layout.html" %}

{% block body %}
    <h1>Add task</h1>
    <form action="{% url 'mytasks:add' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
    <a href="{% url 'mytasks:index' %}">View task</a>
{% endblock %}

ProjectMK/mytasks/templates/mytasks/index.html
{% extends "mytasks/layout.html" %}

{% block body %}

    <h1>Tasks</h1>
    <ul>
    {% for task in tasks %}
        <li>{{task}}</li>
    {% empty %}
        <li>No tasks.</li>
    {% endfor %}
    </ul>
    <a href="{% url 'mytasks:add' %}">Add a new task</a>
{% endblock %}

ProjectMK/mytasks/templates/mytasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

ProjectMK/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <tile>Is it new year</tile>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if newyear %}
        <h1>YES</h1>
        {% else %}
        <h1>NO</h1>
        {% endif %}
    </body>
</html>

ProjectMK/tasks/templates/tasks/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        <ul>
        {% for task in tasks %}
            <li>{{task}}</li>
        {% endfor %}
        </ul>
    </body>
</html>